services:
  timescale:
    container_name: "pilosa-timescale-db"
    image: timescale/timescaledb-ha:pg16
    volumes:
      - ./.data/timescale:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pilosa
      POSTGRES_PASSWORD: pilosa
      POSTGRES_DB: pilosa
